### PR TITLE
Contributed - web UI/UX and themes - elegant & aqua

### PR DESCRIPTION
**Pull request by DalpatRathore**
### All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by Ashutosh00710** [comment]
Hey! @DalpatRathore, thank you for contributing to this project 🚀. 

Before I review this PR, Can please:
- Write a small description or some bullets about the changes you have made
- Some relevant screenshots or GIFs representing your graphical changes (if any)

This will help while reviewing the code.

**Comment by DalpatRathore** [comment]
Hello! @Ashutosh00710
  I have contributed the below-given changes in the “**GitHub-Readme-Activity-Graph**”  repo:

> **Web UI/UX Changes:**

1. Made UI Changes with logo and footer
 web-ui


2. Added Loading Animation - when user data fetching for graph
 loader

3. Added footer section with text & link.
footer



> **Added Two Themes:**
1. Elegant
elegant

2. Aqua
aqua


Thank you for developing this activity graph. It not only looks good but also persuades programmers to keep coding and contributing more for plotting this elegant graph on their Github profile.

Thanks & Regards.

**Review by Ashutosh00710 — APPROVED** [review]
Awesome changes 🎉🎉 @DalpatRathore, thanks for improving the quality of this project. Merging this PR with main. Changes will reflect in the production soon 🚀.

Keep Contributing to Open Source 😀

**Comment by DalpatRathore** [comment]
Thank you @Ashutosh00710  for appreciating my contributions.

Stay happy & blessed.

*Happy Coding!*

**Pull request merged**
