### PR TITLE
Added hide border option

### PR DESCRIPTION
**Pull request by DenverCoder1**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions
1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### Feature changes

* Added a `hide_border` query parameter which will set the stroke of the outer rectangle to `#0000` (transparent) when set to true.
* Using both the `theme` parameter and other options will allow the user to use a theme as their "base" and overwrite specific properties. This allows the user, for example, to pick a theme and decide to hide the border or change the background while keeping the other options from the theme.

### Screenshots

http://localhost:5100/graph?username=DenverCoder1&theme=redical

image

http://localhost:5100/graph?username=DenverCoder1&theme=redical&hideBorder=true

image

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Closes #51.

Will add another commit to update the readme.

**Review by Ashutosh00710 — APPROVED** [review]
Awesome changes @DenverCoder1. Thanks for contributing in this project. Merging this to main.

**Comment by Kshitij978** [comment]
> Closes #51.
> 
> Will add another commit to update the readme.

Okay, go for it. 👍🏼

**Comment by DenverCoder1** [comment]
@Kshitij978 It seems this PR is closed, should I open another PR to add it?

**Comment by Ashutosh00710** [comment]
Yes, @DenverCoder1 🙂

**Comment by DenverCoder1** [comment]
> Yes, @DenverCoder1 🙂

Done. #53 

Thanks for allowing me to contribute to this awesome project! 🎉

**Comment by Ashutosh00710** [comment]
You're welcome 🙂 @DenverCoder1

**Comment by Kshitij978** [comment]
@DenverCoder1  Changes have been deployed. This feature is now available in production. 🎉
Thank you for adding value to this project. 🙌🏼

**Comment by DenverCoder1** [comment]
> @DenverCoder1 Changes have been deployed. This feature is now available in production. 🎉

Awesome! 🎉

I tried it out and it seems `hideBorder` works but `hide_border` doesn't. I changed the name of the parameter when adding the docs in #53 and it seems that the newest change may have not been deployed.

**Comment by Ashutosh00710** [comment]
Deployed Again. Fixed this. 
That was by mistake. 
Thanks for reminding me. 

Now check `hide_border` parameter.

**Comment by DenverCoder1** [comment]
@Ashutosh00710 It works! 🎉

**Comment by Ashutosh00710** [comment]
@DenverCoder1, I visited your profile and it was really awesome. Your color choice for the activity graph was so good. 

I was thinking about adding your color combination as one of our themes. 

- Do you agree to this?
- If yes, can you name the theme and make a PR for issue #25 or you want us to add this?
- If no, no problem that's completely fine.

**Comment by DenverCoder1** [comment]
@Ashutosh00710 Sure!

**Pull request merged**
