### PR TITLE
Implemented height option to allow consumers to change the height of the chart

### PR DESCRIPTION
**Pull request by jmloudis**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by jmloudis** [comment]
https://github.com/jmloudis/github-readme-activity-graph/commit/45c9ff26bc9ab2e03a33c10d6741c54098e5f3e2#commitcomment-101172123

**Comment by jmloudis** [comment]
Hey team,

Would you be able to review the changes and let me know where I went wrong. I thought I followed the submission guidelines. Thanks!

**Comment by Ashutosh00710** [comment]
Hi @jmloudis, thank you for your contribution, changes are looking good to me but before merging it to main can you please share some screenshots of different heights??

**Comment by jmloudis** [comment]
Hey @Ashutosh00710,

Yes of course. I left a link to the comment above but I can copy the message with the screenshots. Here you go.

Implemented height query option for chart instead of having a hard coded value. The consumer can query any height value in between the range [200,600]. Any value outside of the range will revert to the max / min value of either 200 or 600. If no height option is configured, the default value of 420 will be displayed. 

Default height: 420
Default-height

Smallest height: 200 
Smallest-height

Largest height: 600
Largest-height

**Review by Ashutosh00710 — CHANGES_REQUESTED** [review]
Changes are looking good to me but one thing is missing though, README.md is not updated for height parameter. Can you do the changes and ping in the comment?

**Comment by jmloudis** [comment]
Will do! I will work on that and create another commit when I get home from work tonight.

**Pull request merged**
