### PR TITLE
Feat: gradient-color heading

### PR DESCRIPTION
**Pull request by DalpatRathore**
Hello @Ashutosh00710 and @Kshitij978 
    &nbsp;&nbsp;&nbsp;&nbsp; I have contributed **gradient-color heading** this time, as can be seen in the below-given screenshots. Please review this change.
- dark mode view 
 gradient-heading-2

- light mode view
gradient-heading-1

### CODE REVIEW

**Review by Kshitij978 — CHANGES_REQUESTED** [review]
Hello, @DalpatRathore. Thanks for the effort! ✨ Gradient colors used are not much appealing. Maybe the relevant combination of only two colors that would blend perfectly with the whole UI will work?

**Comment by DalpatRathore** [comment]
Thanks, @Kshitij978  for reviewing. You suggest which color combination you want or we should stay with no colors (original).

**Comment by Kshitij978** [comment]
@DalpatRathore Sure, I'll experiment with few colors and let you know. In the meantime you can visit [here](https://uigradients.com/#SweetMorning) and try too. 😀

**Comment by Kshitij978** [comment]
Hi! @DalpatRathore, Sorry for reverting back late. Let's keep it original for now. I'm doing some changes to the website. We will decide about gradient after the changes.

**Comment by DalpatRathore** [comment]
No problem @Kshitij978. Should I close this pull request or let it remain till changes from your side.

**Comment by Kshitij978** [comment]
@DalpatRathore I have created a new discussion tab for this pull request. We will discuss about it there. For now I'm closing this pull request.

**Comment by DalpatRathore** [comment]
All right. One more thing I wanna ask u is that I have tinkered around this web logo, therefore should I create a new pull request with an `enhancement` label or you wanna combine this also with gradient heading discussion.

**Comment by Kshitij978** [comment]
@DalpatRathore can you send a screenshot in discussion?

**Comment by DalpatRathore** [comment]
Thanks.

_Happy Coding_

**Pull request closed without merging**
