### PR TITLE
change react.png

### PR DESCRIPTION
**Pull request by tranthaituananh**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by tranthaituananh** [comment]
add merko, vue & tokyo-night theme style

**Review by Ashutosh00710 — CHANGES_REQUESTED** [review]
@tranthaituananh changes are looking good to me but I can see some extra files being added.

- `asset/.DS_Store`
- `src/.DS_Store`

Can you please remove these files

**Comment by tranthaituananh** [comment]
@Ashutosh00710 I'm so sorry for this mistake, I've already deleted it

**Comment by Ashutosh00710** [comment]
@tranthaituananh nothing to sorry about, thank you for your valuable contribution 🎉. Keep contributing, Keep Growing 🚀

**Pull request merged**
