### PR TITLE
Added cobalt theme

### PR DESCRIPTION
**Pull request by tranthaituananh**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by tranthaituananh** [comment]
I added 2 new themes (material and cobalt) to this project

**Review by Kshitij978 — CHANGES_REQUESTED** [review]
Hi @tranthaituananh can you please change the file format from `jpg` to `svg` or `png` in the asset folder?

**Comment by tranthaituananh** [comment]
Hi @Kshitij978 , I changed jpg to png for 2 screenshot (material & cobalt)

**Review by Kshitij978 — COMMENTED** [review]
Hi @tranthaituananh Changes are looking good! 👍

**Pull request merged**
