### PR TITLE
Add Deploy to Replit Support

### PR DESCRIPTION
**Pull request by valetzx**
### All Submissions

- [√] Have you followed the guidelines in our Contributing document?
- [√] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [√] Does your submission pass tests?
2. [√] Have you lint your code locally prior to submission?

### Changes to Core Features

- [√] Have you added an explanation of what your changes do and why you'd like us to include them?
- [√] Have you written new tests for your core changes, as applicable?
- [√] Have you successfully ran tests with your changes locally?

### You can add this icon to your README 

<a href="https://repl.it/github/Ashutosh00710/github-readme-activity-graph">
  Run on Repl.it
</a>

### CODE REVIEW

**Comment by valetzx** [comment]
DEMO VIEW : https://readme.piged.repl.co

[](https://readme.piged.repl.co/graph?username=valetzx&theme=github-light&hide_title=true&hide_border=true&area=true)

**Comment by Ashutosh00710** [comment]
Hey @valetzx, apologies for late response, I have a few doubts,

- Is it mandatory to put [.replit](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/129/files#diff-dabe747bc6b60b9f68c11dfbf2fbc44d3d37bd289e8f7fdc88647cd697d5cbae), [replit.nix](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/129/files#diff-22b9579023f67739db589390eb7a4ed9a7a02b017e885858758780f8ec923864), [replit.sh](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/129/files#diff-578567a13bf0e8f714444a2b7767c1b62b823cd3193f186cadacafc3bf2f674f) files at the root. Or we can move them to a dedicated folder as well?
- With the above point being said can you make a small change on `README.md` as well, mentioning the steps to follow in order to deploy on `repl.it` and place the **replit** button right there.

**Comment by valetzx** [comment]
Thanks  
1. If want use deploy on `repl.it` bottom the `.replit, replit.nix, replit.sh` files need at the root. I know it will be a little unsightly. or you can make a replit branch, use this branch to store `.replit, replit.nix, replit.sh` files and other README sth.
2. I will read `README.md` again and make some changes

**Comment by Ashutosh00710** [comment]
Got you @val, let me know when you are done with you changes in readme. I'll review and merge it to master.

**Comment by valetzx** [comment]
OK i done the just right haha, the `replit.it` button will work after you merge it to master. Thanks!

**Comment by valetzx** [comment]
@Ashutosh00710 Its all done, fix the github token link description

**Comment by Ashutosh00710** [comment]
Thanks @valetzx for this valuable contribution to this project.

**Pull request merged**
