### PR TITLE
added gotham theme (ref: #25)

### PR DESCRIPTION
**Pull request by sreyan-ghosh**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

**SOLVES ISSUE** #25 partially.

**Changes Made**
1. File modified = `styles/theme.ts`
2. Added params for `gotham` theme taking hex values from other repos like `github-readme-stats`. [Here](https://camo.githubusercontent.com/cf6b1611c3b67ce94d8663a4b6ae14dc135b04a1233cb2bf01200d50aa0ad7b5/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616e7572616768617a72612673686f775f69636f6e733d7472756526686964653d636f6e74726962732c7072732663616368655f7365636f6e64733d3836343030267468656d653d676f7468616d) is the inspiration.

**SCREENSHOTS**
I have personally used this in my own [`README.md`](https://github.com/sreyan-ghosh/sreyan-ghosh). Here is a preview of it in development.

image

**NOTE**
Please consider this PR as a submission towards **Hacktoberfest 2021** and add the `hacktoberfest-accepted` label.

### CODE REVIEW

**Comment by Kshitij978** [comment]
@sreyan-ghosh Please remove the package-lock.json from the commit and add a screenshot of your theme in **svg** format to [THEMES.md](https://github.com/Ashutosh00710/github-readme-activity-graph/blob/df68d8449e5f3449c24ae603b230cd9493839b2d/THEMES.md)

**Comment by sreyan-ghosh** [comment]
okay, i'll let you know when i am done with that

**Comment by sreyan-ghosh** [comment]
Hi @Kshitij978, I have done what had been asked. Cheers. 😃

**Comment by Ashutosh00710** [comment]
@sreyan-ghosh your theme is now available in production 🚀

**Pull request merged**
