### PR TITLE
Added icon to web interface

### PR DESCRIPTION
**Pull request by MagicLike**
### Description
I implemented the logo.png under /asset in the index.html, so that it will be shown as favicon in the web interface.

___
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [ ] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?
___

### Screenshot
icon

### CODE REVIEW

**Review by Kshitij978 — APPROVED** [review]
@MagicLike Thank you for your valuable contribution! ✨ Changes are looking good. Merging it to main.

**Comment by MagicLike** [comment]
@Kshitij978 Would it be possible to add me to the list of contributors?

**Comment by Kshitij978** [comment]
Hey, @MagicLike! You can add yourself to the list and make a pull request, I will merge it. Or if you want us to add you to the list?

**Comment by MagicLike** [comment]
Pull request is there! 🎉

**Pull request merged**
