### PR TITLE
Display actual dates on x-axis

### PR DESCRIPTION
**Pull request by andinoriel**
### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

These changes implement functionality mentioned in issues #64, #78 which propose to add captions to the contributions as actual dates, instead of simply listing from 1 to 31.

image_2021-09-04_16-58-06

### CODE REVIEW

**Review by Kshitij978 — APPROVED** [review]
I appreciate the effort. This is a great addition to the quality of the project. Thanks for your awesome contribution! 🎉

**Comment by Ashutosh00710** [comment]
@andinoriel the graph is now giving a browser compatibility issue #81
Can you propose any solution for that?

**Comment by andinoriel** [comment]
> 
> 
> @andinoriel the graph is now giving a browser compatibility issue #81
> Can you propose any solution for that?

I'll try to fix it soon

**Comment by Ashutosh00710** [comment]
Hi @andinoriel, changes proposed in this PR have been reverted temporarily. 
The reasons are,
- The cross-browser compatibility issue.
- Cover some corner cases regarding timezones.

We will re-deploy this feature soon. This feature is a great addition, without a doubt.

**Comment by Ashutosh00710** [comment]
Hi, @andinoriel your changes are now available in production. 🚀
We don't have any solution for Safari yet. Let us know if you find anything.

**Pull request merged**
